CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT UNIQUE,
    password_hash TEXT,
    avatar_url TEXT,
    email TEXT
);

CREATE TABLE IF NOT EXISTS user_preferences (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    favorite_genres TEXT DEFAULT '[]',
    favorite_people TEXT DEFAULT '[]',
    favorite_movie_ids TEXT DEFAULT '[]',
    people_seed_movie_ids TEXT DEFAULT '[]',
    onboarding_completed_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    profile_genres TEXT DEFAULT '[]',
    profile_people TEXT DEFAULT '[]',
    profile_people_data TEXT DEFAULT '[]',
    profile_movie_ids TEXT DEFAULT '[]',
    profile_soundtrack TEXT DEFAULT '{}',
    profile_description TEXT DEFAULT '',
    owned_streaming_services TEXT DEFAULT '[]',
    tutorial_completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_ratings (
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    movie_id INTEGER,
    rating DOUBLE PRECISION,
    title TEXT,
    poster_url TEXT,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, movie_id)
);

CREATE TABLE IF NOT EXISTS playlists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    name TEXT
);

CREATE INDEX IF NOT EXISTS idx_playlists_user_id ON playlists(user_id);

CREATE TABLE IF NOT EXISTS playlist_items (
    playlist_id INTEGER REFERENCES playlists(id) ON DELETE CASCADE,
    movie_id INTEGER,
    title TEXT,
    poster_url TEXT,
    rating DOUBLE PRECISION,
    added_at TIMESTAMP,
    sort_index INTEGER,
    primary_genre TEXT,
    subscription_provider_names TEXT DEFAULT '[]',
    metadata_updated_at TIMESTAMP,
    UNIQUE (playlist_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_playlist_items_playlist_sort ON playlist_items(playlist_id, sort_index);
CREATE INDEX IF NOT EXISTS idx_playlist_items_playlist_added_at ON playlist_items(playlist_id, added_at);
CREATE INDEX IF NOT EXISTS idx_playlist_items_movie_id ON playlist_items(movie_id);

CREATE TABLE IF NOT EXISTS follows (
    follower_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    followed_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (follower_id, followed_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_followed_id ON follows(followed_id);

CREATE TABLE IF NOT EXISTS blocked_users (
    blocker_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    blocked_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (blocker_id, blocked_id)
);

CREATE INDEX IF NOT EXISTS idx_blocked_users_blocked_id ON blocked_users(blocked_id);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    movie_id INTEGER,
    title TEXT,
    poster_url TEXT,
    rating DOUBLE PRECISION,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reviews_user_created_at ON reviews(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_movie_id ON reviews(movie_id);

CREATE TABLE IF NOT EXISTS review_likes (
    review_id INTEGER REFERENCES reviews(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (review_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_review_likes_user_id ON review_likes(user_id);

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review_id INTEGER REFERENCES reviews(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    parent_id INTEGER REFERENCES comments(id) ON DELETE SET NULL,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_comments_review_parent_created ON comments(review_id, parent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    actor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    type TEXT,
    review_id INTEGER REFERENCES reviews(id) ON DELETE CASCADE,
    comment_id INTEGER REFERENCES comments(id) ON DELETE CASCADE,
    is_read INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_read_created ON notifications(user_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_review_id ON notifications(review_id);
CREATE INDEX IF NOT EXISTS idx_notifications_comment_id ON notifications(comment_id);

CREATE TABLE IF NOT EXISTS direct_conversations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_one_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    user_two_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    user_one_last_read_message_id INTEGER DEFAULT 0,
    user_two_last_read_message_id INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_one_id, user_two_id)
);

CREATE INDEX IF NOT EXISTS idx_direct_conversations_user_one ON direct_conversations(user_one_id);
CREATE INDEX IF NOT EXISTS idx_direct_conversations_user_two ON direct_conversations(user_two_id);

CREATE TABLE IF NOT EXISTS direct_messages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id INTEGER REFERENCES direct_conversations(id) ON DELETE CASCADE,
    sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    content TEXT,
    movie_id INTEGER,
    movie_title TEXT,
    movie_poster_url TEXT,
    movie_rating DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reply_to_message_id INTEGER REFERENCES direct_messages(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_direct_messages_conversation_id_id ON direct_messages(conversation_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_direct_messages_sender_id ON direct_messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_direct_messages_reply_to ON direct_messages(reply_to_message_id);

CREATE TABLE IF NOT EXISTS mobile_devices (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    platform TEXT,
    token TEXT UNIQUE,
    app_version TEXT,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mobile_devices_user_id ON mobile_devices(user_id);

CREATE TABLE IF NOT EXISTS password_reset_codes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    code_hash TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_password_reset_codes_user_created ON password_reset_codes(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS web_push_subscriptions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    endpoint TEXT UNIQUE,
    subscription_json TEXT,
    user_agent TEXT,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_web_push_subscriptions_user_id ON web_push_subscriptions(user_id);

CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recommendation_impressions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id TEXT,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    movie_id INTEGER,
    mode TEXT,
    algorithm_variant TEXT,
    rank INTEGER,
    reason TEXT,
    seed_movie_id INTEGER,
    seed_title TEXT,
    seed_similarity DOUBLE PRECISION,
    shown_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP,
    reaction_type TEXT,
    reaction_rating DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_recommendation_impressions_user_movie ON recommendation_impressions(user_id, movie_id, shown_at);
CREATE INDEX IF NOT EXISTS idx_recommendation_impressions_feedback ON recommendation_impressions(user_id, responded_at, algorithm_variant);

CREATE TABLE IF NOT EXISTS moderation_reports (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reporter_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    target_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    target_review_id INTEGER REFERENCES reviews(id) ON DELETE SET NULL,
    target_comment_id INTEGER REFERENCES comments(id) ON DELETE SET NULL,
    target_conversation_id INTEGER REFERENCES direct_conversations(id) ON DELETE SET NULL,
    reason TEXT,
    details TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_moderation_reports_reporter ON moderation_reports(reporter_user_id);
